In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.model_selection import cross_val_score

# Importing Feature Selection Modesl
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import RFE
from sklearn.model_selection import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.feature_selection import chi2
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectFromModel

# Importing Learning Models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis


In [2]:
taiwan_bankruptcy = pd.read_csv("data.csv")

taiwan_bankruptcy.head()

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0          1                                           0.370594          
1          1                                           0.464291          
2          1                                           0.426071          
3          1                                           0.399844          
4          1                                           0.465022          

    ROA(A) before interest and % after tax  \
0                                 0.424389   
1                                 0.538214   
2                                 0.499019   
3                                 0.451265   
4                                 0.538432   

    ROA(B) before interest and depreciation after tax  \
0                                           0.405750    
1                                           0.516730    
2                                           0.472295    
3                                           0.457733    
4                                           0.522298    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                 0.601457                      0.601457   
1                 0.610235                      0.610235   
2                 0.601450                      0.601364   
3                 0.583541                      0.583541   
4                 0.598783                      0.598783   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                0.998969                    0.796887   
1                0.998946                    0.797380   
2                0.998857                    0.796403   
3                0.998700                    0.796967   
4                0.998973                    0.797366   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                      0.808809                                      0.302646   
1                      0.809301                                      0.303556   
2                      0.808388                                      0.302035   
3                      0.808966                                      0.303350   
4                      0.809304                                      0.303475   

   ...   Net Income to Total Assets   Total assets to GNP price  \
0  ...                     0.716845                    0.009219   
1  ...                     0.795297                    0.008323   
2  ...                     0.774670                    0.040003   
3  ...                     0.739555                    0.003252   
4  ...                     0.795016                    0.003878   

    No-credit Interval   Gross Profit to Sales  \
0             0.622879                0.601453   
1             0.623652                0.610237   
2             0.623841                0.601449   
3             0.622929                0.583538   
4             0.623521                0.598782   

    Net Income to Stockholder's Equity   Liability to Equity  \
0                             0.827890              0.290202   
1                             0.839969              0.283846   
2                             0.836774              0.290189   
3                             0.834697              0.281721   
4                             0.839973              0.278514   

    Degree of Financial Leverage (DFL)  \
0                             0.026601   
1                             0.264577   
2                             0.026555   
3                             0.026697   
4                             0.024752   

    Interest Coverage Ratio (Interest expense to EBIT)   Net Income Flag  \
0                                           0.564050                   1   
1                                           0.570175                   1   
2                                           0.563706                   1   
3                                           0.564663                   1   
4                        

In [3]:
y = taiwan_bankruptcy["Bankrupt?"]
X = taiwan_bankruptcy.drop(columns = ["Bankrupt?"])

In [7]:
taiwan_bankruptcy.describe()

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count  6819.000000                                        6819.000000          
mean      0.032263                                           0.505180          
std       0.176710                                           0.060686          
min       0.000000                                           0.000000          
25%       0.000000                                           0.476527          
50%       0.000000                                           0.502706          
75%       0.000000                                           0.535563          
max       1.000000                                           1.000000          

        ROA(A) before interest and % after tax  \
count                              6819.000000   
mean                                  0.558625   
std                                   0.065620   
min                                   0.000000   
25%                                   0.535543   
50%                                   0.559802   
75%                                   0.589157   
max                                   1.000000   

        ROA(B) before interest and depreciation after tax  \
count                                        6819.000000    
mean                                            0.553589    
std                                             0.061595    
min                                             0.000000    
25%                                             0.527277    
50%                                             0.552278    
75%                                             0.584105    
max                                             1.000000    

        Operating Gross Margin   Realized Sales Gross Margin  \
count              6819.000000                   6819.000000   
mean                  0.607948                      0.607929   
std                   0.016934                      0.016916   
min                   0.000000                      0.000000   
25%                   0.600445                      0.600434   
50%                   0.605997                      0.605976   
75%                   0.613914                      0.613842   
max                   1.000000                      1.000000   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count             6819.000000                 6819.000000   
mean                 0.998755                    0.797190   
std                  0.013010                    0.012869   
min                  0.000000                    0.000000   
25%                  0.998969                    0.797386   
50%                  0.999022                    0.797464   
75%                  0.999095                    0.797579   
max                  1.000000                    1.000000   

        After-tax net Interest Rate  \
count                   6819.000000   
mean                       0.809084   
std                        0.013601   
min                        0.000000   
25%                        0.809312   
50%                        0.809375   
75%                        0.809469   
max                        1.000000   

        Non-industry income and expenditure/revenue  ...  \
count                                   6819.000000  ...   
mean                                       0.303623  ...   
std                                        0.011163  ...   
min                                        0.000000  ...   
25%                                        0.303466  ...   
50%                                        0.303525  ...   
75%                                        0.303585  ...   
max                                        1.000000  ...   

        Net Income to Total Assets   Total assets to GNP price  \
count                  6819.000000                6.819000e+03   
mean                      0.807760                1.862942e+07   
std                       0.040332                3.764501e+08   
min

In [8]:
taiwan_bankruptcy.groupby('Bankrupt?').size()

Bankrupt?
0    6599
1     220
dtype: int64

In [4]:
# Practice Train-Test Split

from sklearn.model_selection import train_test_split

random_state = 1
test_size = 0.5

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state= random_state, stratify = y)

In [11]:
# Practice  Logistic Regression

from sklearn.linear_model import LogisticRegression

random_state = 1

logit = LogisticRegression(solver= "saga", random_state = random_state)
logit_fit = logit.fit(X_train, y_train)

In [13]:
print(logit_fit.intercept_)
print(logit_fit.coef_)

[-4.96943189e-17]
[[-2.96712011e-17 -3.29953099e-17 -3.23374320e-17 -3.09226019e-17
  -3.09160993e-17 -4.96397745e-17 -3.96422171e-17 -4.02325626e-17
  -1.51191765e-17 -3.88527402e-17 -1.17938897e-10 -2.67757753e-10
  -2.34375339e-17 -1.25246811e-09 -9.38999350e-18 -1.11596626e-17
  -1.11604116e-17 -1.11568903e-17 -1.34972382e-17 -1.62645490e-17
  -1.42804013e-10 -6.57248975e-18 -1.11184976e-17 -1.31671435e-18
  -4.22163980e-17 -3.44433452e-17 -3.44431938e-17 -1.08096275e-17
  -3.50016906e-10  5.96044411e-10 -1.32182190e-17 -1.92559781e-17
  -7.09144482e-11  1.94004024e-11 -3.14060248e-17 -9.82868789e-11
  -1.64294462e-18 -4.80513743e-17 -5.73528458e-19 -1.77238378e-17
   2.15458073e-19 -6.55790667e-18 -1.08809593e-17 -1.97316433e-17
  -9.16803956e-18 -5.17047445e-10 -6.63996454e-10 -1.96434484e-10
   3.16684984e-12 -1.74090764e-18 -4.45227118e-11 -2.08730987e-17
  -4.17923114e-10 -4.46452479e-17 -2.81824381e-17 -3.15024156e-17
  -1.33494858e-17 -3.07082595e-10  2.88569458e-10 -1.51466

In [9]:
y_train_pred = logit_fit.predict(X_train)

print(metrics.classification_report(y_train, y_train_pred))
print(metrics.confusion_matrix(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      3299
           1       0.18      0.02      0.03       110

    accuracy                           0.97      3409
   macro avg       0.58      0.51      0.51      3409
weighted avg       0.94      0.97      0.95      3409

[[3290    9]
 [ 108    2]]


In [6]:
y_test_pred = logit_fit.predict(X_test)

print(metrics.classification_report(y_test, y_test_pred))
print(metrics.confusion_matrix(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      3300
           1       0.00      0.00      0.00       110

    accuracy                           0.96      3410
   macro avg       0.48      0.50      0.49      3410
weighted avg       0.94      0.96      0.95      3410

[[3288   12]
 [ 110    0]]


In [28]:
# Practice Feature Selection 


k = 10
estimator = logit

# Supervised Methods

#Univariate 
SKB_selector = SelectKBest(chi2, k=k).fit(X_train, y_train)

# Model Based
RFECV_selector = RFECV(logit, step=1, cv=5,min_features_to_select = k).fit(X_train, y_train)

clf = ExtraTreesClassifier(n_estimators=50)
clf.fit(X_train, y_train)
tree_selector = SelectFromModel(clf, prefit=True, max_features=k)

selectors = [SKB_selector, RFECV_selector, tree_selector]

In [29]:
for selector in selectors:
    cols = X_train[X_train.columns[selector.get_support(indices=True)]].columns
    print(cols)

Index([' Research and development expense rate', ' Total Asset Growth Rate',
       ' Net Value Growth Rate', ' Quick Ratio', ' Total debt/Total net worth',
       ' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency',
       ' Cash/Current Liability', ' Inventory/Current Liability',
       ' Current Asset Turnover Rate'],
      dtype='object')
Index([' Research and development expense rate',
       ' Interest-bearing debt interest rate', ' Total Asset Growth Rate',
       ' Net Value Growth Rate', ' Accounts Receivable Turnover',
       ' Average Collection Days', ' Inventory Turnover Rate (times)',
       ' Allocation rate per person', ' Quick Assets/Current Liability',
       ' Cash/Current Liability', ' Inventory/Current Liability',
       ' Cash Turnover Rate', ' Total assets to GNP price'],
      dtype='object')
Index([' Debt ratio %', ' Net worth/Assets', ' Borrowing dependency',
       ' Net profit before tax/Paid-in capital', ' Cash/Current Liability',
       

In [34]:
models = []
models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))

# evaluate each model in turn
results = []
names = []

for name, model in models:
    kfold = StratifiedKFold(n_splits=10, random_state= 1, shuffle=True)
    cv_results = cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    print('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))

LR: 0.964800 (0.002259)
LDA: 0.957762 (0.013444)
KNN: 0.967439 (0.001578)
CART: 0.949252 (0.007188)
NB: 0.080082 (0.010896)


In [35]:

y_train_NB =GaussianNB().fit(X_train, y_train).predict(X_train)

print(metrics.classification_report(y_train, y_train_NB))
print(metrics.confusion_matrix(y_train, y_train_NB))

              precision    recall  f1-score   support

           0       1.00      0.05      0.09      3299
           1       0.03      1.00      0.07       110

    accuracy                           0.08      3409
   macro avg       0.52      0.52      0.08      3409
weighted avg       0.97      0.08      0.09      3409

[[ 163 3136]
 [   0  110]]
